version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: auto_d_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - auto-d-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto_d_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - auto-d-network

  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autod
      MYSQL_USER: autod
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - auto-d-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  composer:
    image: composer:latest
    user: "1000:1000"
    container_name: auto_d_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - auto-d-network

  npm:
    image: node:16
    container_name: auto_d_npm
    user: "1000:1000"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm", "install"]

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto_d_artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["/bin/sh", "-c", "php artisan $*"]
    networks:
      - auto-d-network

networks:
  auto-d-network:
    driver: bridge
